name: efnd
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.7
  - pip
  - pip:
      - tqdm
      - pandas
      - transformers
      - scikit-learn
      - tensorboardx
      - numpy~=1.24.3
      - openai
